### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ibecir** [vmujic1/ooad-grupa4-eApoteka#15]
1. ER dijagram, nema AspNetUser-a a moramo koristiti tu klasu, raspravit cemo za vrijeme vjezbi
2. Sequence dijagram je previse jednostavan, raspravit cemo za vrijeme vjezbi takodjer

**Comment by apasalic10** [comment]
Poštovani, možete li samo pregledati dijagram sekvence i javiti je li sve uredu? @ibecir

**Comment by apasalic10** [comment]
Takođe urađen je i ER dijagram pa i to provjerite. @ibecir
